{
 "title": "MyApp monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(http_request_duration_seconds_bucket{path=\"/health\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Health requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{path=~\"/health\",instance=~\"$instance\",le=\"+Inf\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hello page requests count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{path=~\"/hello\",instance=~\"$instance\",le=\"+Inf\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hello request rpm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(http_request_duration_seconds_bucket{path=\"/hello\",instance=~\"$instance\",le=\"+Inf\"}[1m])) by (instance), 0.001) * 60\n\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}